"""add roles

Revision ID: 868cf42a68be
Revises: d5524280ecee
Create Date: 2020-01-20 14:51:58.892618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '868cf42a68be'
down_revision = 'd5524280ecee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    # ### end Alembic commands ###
