"""add null

Revision ID: d5524280ecee
Revises: caf427204e3b
Create Date: 2020-01-20 14:49:15.448724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5524280ecee'
down_revision = 'caf427204e3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blogs', 'blog_author',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('blogs', 'blog_content',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('blogs', 'blog_title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blogs', 'blog_title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('blogs', 'blog_content',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('blogs', 'blog_author',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
