"""add relatio

Revision ID: df32987063fc
Revises: 552f900ddd34
Create Date: 2020-01-20 15:07:10.649111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df32987063fc'
down_revision = '552f900ddd34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blogs', 'blog_author',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('blogs', 'blog_content',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('blogs', 'blog_title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blogs', 'blog_title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('blogs', 'blog_content',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('blogs', 'blog_author',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
